#!/usr/bin/env bash
# Check if Nginx is installed
if [ ! -x "$(command -v nginx)" ]; then
    echo "Nginx is not installed. Please run 1-install_nginx_web_server first."
    exit 1
fi

# Create a custom configuration file for the redirection
echo "location /redirect_me {" > /etc/nginx/sites-available/redirect_me
echo "    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;" >> /etc/nginx/sites-available/redirect_me
echo "}" >> /etc/nginx/sites-available/redirect_me

# Create a symbolic link to enable the new configuration
ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Reload Nginx to apply changes
service nginx reload

# Display a message indicating successful configuration
echo "Nginx redirection configured successfully."
