#!/usr/bin/env bash
# Check if Nginx is installed
if [ ! -x "$(command -v nginx)" ]; then
    echo "Nginx is not installed. Please run 1-install_nginx_web_server first."
    exit 1
fi

# Create a custom configuration file for the 404 page
echo "server {" > /etc/nginx/sites-available/custom_404
echo "    listen 80 default_server;" >> /etc/nginx/sites-available/custom_404
echo "    listen [::]:80 default_server;" >> /etc/nginx/sites-available/custom_404
echo "    root /var/www/html;" >> /etc/nginx/sites-available/custom_404
echo "    error_page 404 /custom_404.html;" >> /etc/nginx/sites-available/custom_404
echo "    location = /custom_404.html {" >> /etc/nginx/sites-available/custom_404
echo "        internal;" >> /etc/nginx/sites-available/custom_404
echo "        return 404 'Ceci n'est pas une page';" >> /etc/nginx/sites-available/custom_404
echo "    }" >> /etc/nginx/sites-available/custom_404
echo "}" >> /etc/nginx/sites-available/custom_404

# Create a symbolic link to enable the new configuration
ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Reload Nginx to apply changes
service nginx reload

# Display a message indicating successful configuration
echo "Nginx custom 404 page configured successfully."
