#!/usr/bin/env bash
# Update package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Get the hostname of the server
hostname=$(hostname)

# Create a new Nginx configuration file for custom header
echo "add_header X-Served-By $hostname;" | sudo tee /etc/nginx/conf.d/custom_header.conf

# Restart Nginx to apply changes
sudo service nginx restart
