#!/usr/bin/env bash
# This script displays the PID, along with the process name, of processes whose name contain the word bash
for pid in /proc/*/cmdline; do
    if grep -q 'bash' "$pid"; then
        pid_number=$(basename "$(dirname "$pid")")
        process_name=$(tr '\0' ' ' < "$pid" | awk '{print $1}')
        echo "PID: $pid_number, Process Name: $process_name"
    fi
done
